### ISSUE TITLE
has() macro

### ISSUE THREAD

**Issue by Jastrzebowski** [ChromeGG/cel-js#32]
@ChromeGG thank you for providing this library. It's great to see a simple CEL library for the JS ecosystem!

The library is working great as long as the context is predictable. Unfortunately, even when typed, the JS world is full of optional properties. As dealing with `undefined` is a requirement, I thought I would happily introduce it to the library. 

I want the macro to have the following form:

```
has(message.field) // true if `field` is defined on `message` false otherwise
```

Are there any constraints that stopped you from adding this behaviour?

**Comment by ChromeGG** [comment]
Hi @Jastrzebowski,  thanks for the feedback!

From technical POV - there are no constraints.
The only constraint is my limited time. Maybe I'll find a while this weekend. If no, feel free to implement it, happy to review :)

**Comment by Jastrzebowski** [comment]
Perfect! I'm half there. I still need to fix some edge cases, and I plan to publish my PR today. Miłego weekend!
